<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nunit_schema_2.5.xsd" name="Pester" total="2" errors="0" failures="1" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2017-04-07" time="06:45:20">
  <environment user="Administrator" machine-name="WIN-TMO80QKEEO6" cwd="C:\repo\github.com\theThreeRs.Languages.Powershell" user-domain="WIN-TMO80QKEEO6" platform="Microsoft Windows Server 2012 R2 Standard|C:\Windows|\Device\Harddisk0\Partition2" nunit-version="2.5.8.0" os-version="6.3.9600" clr-version="4.0.30319.42000" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite type="TestFixture" name="Pester" executed="True" result="Failure" success="False" time="2.4184" asserts="0" description="Pester">
    <results>
      <test-suite type="TestFixture" name="C:\repo\github.com\theThreeRs.Languages.Powershell\Public\Connect-FTPServer.tests.ps1" executed="True" result="Failure" success="False" time="2.4184" asserts="0" description="C:\repo\github.com\theThreeRs.Languages.Powershell\Public\Connect-FTPServer.tests.ps1">
        <results>
          <test-suite type="TestFixture" name="Connect-FTPServer Function Basic Tests" executed="True" result="Success" success="True" time="0" asserts="0" description="Connect-FTPServer Function Basic Tests">
            <results />
          </test-suite>
          <test-suite type="TestFixture" name="Connect-FTPServer" executed="True" result="Failure" success="False" time="2.4184" asserts="0" description="Connect-FTPServer">
            <results>
              <test-suite type="TestFixture" name="Running with InValid Uri/Login arguments" executed="True" result="Success" success="True" time="0.2823" asserts="0" description="Running with InValid Uri/Login arguments">
                <results>
                  <test-case description="Test1: Without Correct Uri/Login should Throw Exception" name="Connect-FTPServer.Running with InValid Uri/Login arguments.Test1: Without Correct Uri/Login should Throw Exception" time="0.2823" asserts="0" success="True" result="Success" executed="True" />
                </results>
              </test-suite>
              <test-suite type="TestFixture" name="Running with Valid Parametersets" executed="True" result="Failure" success="False" time="2.1361" asserts="0" description="Running with Valid Parametersets">
                <results>
                  <test-case description="Test2: With Valid Uri/Login Should Not Throw Exception" name="Connect-FTPServer.Running with Valid Parametersets.Test2: With Valid Uri/Login Should Not Throw Exception" time="2.1361" asserts="0" success="False" result="Failure" executed="True">
                    <failure>
                      <message>Expected: the expression not to throw an exception. Message was {@{Exception=Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server"; Reason=MethodInvocationException; Target=; Script=C:\repo\github.com\theThreeRs.Languages.Powershell\Public\Connect-FTPServer.ps1; Line=116; Column=15}}
    from C:\repo\github.com\theThreeRs.Languages.Powershell\Public\Connect-FTPServer.ps1:135 char:17
    +                 throw $info
    +                 ~~~~~~~~~~~</message>
                      <stack-trace>at &lt;ScriptBlock&gt;, C:\repo\github.com\theThreeRs.Languages.Powershell\Public\Connect-FTPServer.tests.ps1: line 38
38:        {Connect-FTPServer -Uri $($ValidParamHash.Uri.AbsoluteUri) -Credential $ValidParamHash.PSCredential} | Should -LegacyArg1 Not -LegacyArg2 Throw
</stack-trace>
                    </failure>
                  </test-case>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>